title: Jekyll Netlify CMS
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the basic Jekyll starter site, with Netlify CMS integrated and using
  Netlify Identity for authentication.
